#ex_2 code		
source(file="TRRUST_network.R")		
set.seed(2235)		
trrust <- loadTRRUST()		
trrust <- fixColumns(trrust)		
setMode(2)		
genes <- randomGenes(trrust,10)		
trrust <- filterGenes(trrust,genes)		
nodes <- getNodes(trrust)		
edges <- getEdges (trrust)		
nodes <- getWeights(nodes,edges)		
nodes <- getClusters(nodes,edges)		
edges <- getPMIDs(edges,trrust)		
edges <- getAction(edges,trrust)		
visGraph(nodes,edges)		
exportVis("ex_2")

