var milestones = [
   {
      "url": "https://api.github.com/repos/hyginn/Ontoscope/milestones/3",
      "html_url": "https://github.com/hyginn/Ontoscope/milestones/March%2015",
      "labels_url": "https://api.github.com/repos/hyginn/Ontoscope/milestones/3/labels",
      "id": 1646769,
      "number": 3,
      "title": "March 15",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 3,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-03-15T22:56:30Z",
      "updated_at": "2016-03-15T23:05:01Z",
      "due_on": "2016-03-15T04:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/hyginn/Ontoscope/milestones/1",
      "html_url": "https://github.com/hyginn/Ontoscope/milestones/March%2022",
      "labels_url": "https://api.github.com/repos/hyginn/Ontoscope/milestones/1/labels",
      "id": 1646764,
      "number": 1,
      "title": "March 22",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 5,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-03-15T22:53:18Z",
      "updated_at": "2016-03-15T23:18:40Z",
      "due_on": "2016-03-22T04:00:00Z",
      "closed_at": null
   },
   {
      "url": "https://api.github.com/repos/hyginn/Ontoscope/milestones/2",
      "html_url": "https://github.com/hyginn/Ontoscope/milestones/March%2029",
      "labels_url": "https://api.github.com/repos/hyginn/Ontoscope/milestones/2/labels",
      "id": 1646766,
      "number": 2,
      "title": "March 29",
      "description": "",
      "creator": {
         "login": "thejmazz",
         "id": 1270998,
         "avatar_url": "https://avatars.githubusercontent.com/u/1270998?v=3",
         "gravatar_id": "",
         "url": "https://api.github.com/users/thejmazz",
         "html_url": "https://github.com/thejmazz",
         "followers_url": "https://api.github.com/users/thejmazz/followers",
         "following_url": "https://api.github.com/users/thejmazz/following{/other_user}",
         "gists_url": "https://api.github.com/users/thejmazz/gists{/gist_id}",
         "starred_url": "https://api.github.com/users/thejmazz/starred{/owner}{/repo}",
         "subscriptions_url": "https://api.github.com/users/thejmazz/subscriptions",
         "organizations_url": "https://api.github.com/users/thejmazz/orgs",
         "repos_url": "https://api.github.com/users/thejmazz/repos",
         "events_url": "https://api.github.com/users/thejmazz/events{/privacy}",
         "received_events_url": "https://api.github.com/users/thejmazz/received_events",
         "type": "User",
         "site_admin": false
      },
      "open_issues": 3,
      "closed_issues": 0,
      "state": "open",
      "created_at": "2016-03-15T22:53:42Z",
      "updated_at": "2016-03-15T23:14:20Z",
      "due_on": "2016-03-29T04:00:00Z",
      "closed_at": null
   }
];
var status = "fresh";